
###
GET http://127.0.0.1:8000/ HTTP/1.1


###
POST http://127.0.0.1:8000/api-auth/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin1234!"
}

###
POST http://127.0.0.1:8000/api-auth/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "copy-paste the refresh token here"
}

###
GET http://127.0.0.1:8000/profiles/ HTTP/1.1

###
GET http://127.0.0.1:8000/profiles/1/ HTTP/1.1

###
GET http://127.0.0.1:8000/trips/

###
GET http://127.0.0.1:8000/trips/1/

###
GET http://127.0.0.1:8000/trips/1/images/