# Generated by Django 5.1.4 on 2025-02-06 17:13

import cloudinary.models
import trips.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dchoskzxj/image/upload/v1721990160/yg9qwd4v15r23bxwv5u4.jpg', max_length=255, null=True, validators=[trips.utils.validate_image], verbose_name='image'),
        ),
    ]
