# Generated by Django 5.1.4 on 2025-01-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='profile',
        ),
    ]
