# Generated by Django 5.1.4 on 2025-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='shared',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
