# Generated by Django 5.1.4 on 2025-01-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
