# Generated by Django 5.1.4 on 2025-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_image_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
