# Generated by Django 5.1.4 on 2025-01-11 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at', 'owner']},
        ),
    ]
